# 端口配置
server:
  port: 8181

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://47.106.112.192:6607/test_db1?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ENC(4+1kex/fUUbN8wmc5rpnIg==)
    password: ENC(loRkD8YlX0iPhuPjmVHTPA==)
    driver-class-name: com.mysql.cj.jdbc.Driver
