# 使用的配置文件
spring:
  profiles:
    active: dev

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mapper/configure.xml


#加密
jasypt:
  encryptor:
    bean: encryptorBean
